apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability-demo

resources:
  - namespace.yaml
  - apps/catalog-service.yaml
  - apps/orders-service.yaml
  - observability/prometheus.yaml
  - observability/grafana.yaml
  - observability/otel-collector.yaml
  - observability/tempo.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=../monitoring/prometheus/prometheus.yml
  - name: otel-collector-config
    files:
      - config.yml=../monitoring/otel-collector/config.yml
  - name: tempo-config
    files:
      - tempo.yml=../monitoring/tempo/tempo.yml
  - name: grafana-datasources
    files:
      - datasources.yml=../monitoring/grafana/provisioning/datasources/datasources.yml
  - name: grafana-dashboard-providers
    files:
      - dashboards.yml=../monitoring/grafana/provisioning/dashboards/dashboards.yml
  - name: grafana-dashboard-services-overview
    files:
      - services-overview.json=../monitoring/grafana/dashboards/services-overview.json

